Repository CodingFactory-Repos/Coding-Tools, pull requests merged in 2023-06, with the labels that each got.

#161 G8/feature/timer
  back-end/package-lock.json
  front-end/package-lock.json
  front-end/src/components/common/svg/Timer.vue
  front-end/src/components/retrospective/Timer.vue
  front-end/src/router/index.ts
  front-end/src/views/TimerView.vue
Labels: codeball:needs-careful-review

#261 G10/feature/chat
  back-end/src/app.module.ts
  back-end/src/base/calls/calls.controller.ts
  back-end/src/base/calls/calls.repository.ts
  back-end/src/base/calls/calls.service.ts
  back-end/src/base/calls/interfaces/calls.interface.ts
  back-end/src/common/gateways/chat.global.gateway.ts
  back-end/src/common/middlewares/socket.chat.middleware.ts
  back-end/src/external-modules/chat/chat.module.ts
  back-end/src/main.ts
  front-end/src/components/RollCallComponents/CallsComponent.vue
  front-end/src/components/RollCallComponents/Chat.vue
  front-end/src/components/RollCallComponents/ChatMultiMessage.vue
  front-end/src/components/RollCallComponents/StudentListComponent.vue
  front-end/src/views/calls/GroupsView.vue
  front-end/src/views/calls/RollCallView.vue
Labels: codeball:needs-careful-review

#386 Fix a build compilation for pdf-make
  front-end/src/views/MaterialsView.vue
Labels: bug, codeball:approved

#396 Implement the copy/paste any graphic, nested or not
  front-end/src/lib/pixi-tools-v2/class/containerManager.ts
  front-end/src/lib/pixi-tools-v2/class/normalyzer.ts
  front-end/src/lib/pixi-tools-v2/class/wrappedContainer.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-serialize.ts
Labels: merge when passing

#400 Origin/g6/feature/download pdf
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/agility/AgilityCanvas.vue
  front-end/src/components/agility/UI/ColorPickerOption.vue
  front-end/src/components/agility/UI/DefaultSelectionBox.vue
  front-end/src/components/agility/UI/MiroSelectionBox.vue
  front-end/src/lib/pixi-tools-v2/plugins/managerDownloadPlugin.ts
  front-end/src/lib/pixi-tools-v2/viewportUI.ts
  front-end/src/store/interfaces/project.interface.ts
  front-end/src/store/modules/project.store.ts
Labels: codeball:needs-careful-review

#397 [Delivery] - Merge Visual changes into develop
  back-end/src/base/calls/calls.controller.ts
  back-end/src/base/calls/calls.repository.ts
  back-end/src/base/calls/calls.service.ts
  back-end/src/base/canvasRoom/canvasRoom.service.ts
  back-end/src/base/courses/courses.controller.ts
  back-end/src/base/ideasComments/ideasComments.controller.ts
  back-end/src/base/ideasComments/ideasComments.service.ts
  back-end/src/base/ideasEquipments/ideasEquipments.controller.ts
  back-end/src/base/ideasEquipments/ideasEquipments.service.ts
  back-end/src/base/retrospectives/dto/retrospectives.dto.ts
  back-end/src/base/retrospectives/retrospectives.controller.ts
  back-end/src/base/retrospectives/retrospectives.service.ts
  back-end/src/base/users/users.service.ts
  back-end/src/common/gateways/retrospective.global.gateway.ts
  back-end/src/cron/cron.service.ts
  front-end/.env.example
  front-end/commitlint.config.js
  front-end/src/api/network/socket.io.ts
  front-end/src/components/RollCallComponents/CallsComponent.vue
  front-end/src/components/RollCallComponents/Chat.vue
  front-end/src/components/RollCallComponents/ChatMultiMessage.vue
  front-end/src/components/RollCallComponents/GroupsComponent.vue
  front-end/src/components/RollCallComponents/MakeGroupsComponent.vue
  front-end/src/components/RollCallComponents/ReturnButtonComponent.vue
  front-end/src/components/RollCallComponents/StudentListComponent.vue
  front-end/src/components/account/AccountProfile.vue
  front-end/src/components/account/AccountRelatedProfile.vue
  front-end/src/components/agility/AgilityCanvas.vue
  front-end/src/composables/useSocketRetro.ts
  front-end/src/config/config.ts
  front-end/src/interfaces/advanced-types.interface copy.ts
  front-end/src/lib/pixi-tools-v2/blueprint/empathyMap.ts
  front-end/src/lib/pixi-tools-v2/blueprint/personas.ts
  front-end/src/store/interfaces/material.interface.ts
  front-end/src/store/interfaces/retrospective.interface.ts
  front-end/src/store/retrospective.store.ts
  front-end/src/views/MaterialsView.vue
  front-end/src/views/calls/GroupsView.vue
  front-end/types/shims-mime.d.ts
Labels: codeball:needs-careful-review

#410 G7/feat/cron validation
  back-end/src/base/articles/articles.repository.ts
  back-end/src/base/articles/articles.service.ts
  back-end/src/base/articles/interfaces/articles.interface.ts
  back-end/src/cron/cron.service.ts
Labels: codeball:needs-careful-review

#423 Auto develop TO G8 with Guillaume Maj
  back-end/src/base/articles/articles.repository.ts
  back-end/src/base/articles/articles.service.ts
  back-end/src/base/articles/interfaces/articles.interface.ts
  back-end/src/base/calls/calls.repository.ts
  back-end/src/cron/cron.service.ts
  front-end/src/components/RollCallComponents/GroupsComponent.vue
Labels: codeball:needs-careful-review

#409 Integrate the text-input into the library
  back-end/package-lock.json
  back-end/src/base/articles/articles.service.ts
  back-end/src/base/articles/events/newTutorial.events.req.ts
  back-end/src/base/articles/events/newTutorial.events.ts
  back-end/src/base/groups/groups.module.ts
  back-end/src/base/ideasComments/ideasComments.controller.ts
  back-end/src/base/ideasEquipments/ideasEquipments.controller.ts
  back-end/src/base/retrospectives/dto/retrospectives.dto.ts
  back-end/src/base/retrospectives/events/retrospectives.events.ts
  back-end/src/base/retrospectives/interfaces/retrospectivesRoomInvitation.interface.ts
  back-end/src/base/retrospectives/retrospectives.controller.ts
  back-end/src/base/retrospectives/retrospectives.service.ts
  back-end/src/base/retrospectives/retrospectivesRoomInvitation.repository.ts
  back-end/src/base/users/users.service.ts
  back-end/src/base/users/utils/users.aggregation.ts
  back-end/src/common/gateways/canvas.global.gateway.ts
  back-end/src/common/providers/interfaces/events.interface.ts
  back-end/src/common/providers/mailjet.provider.ts
  front-end/package-lock.json
  front-end/src/api/network/socket.io.ts
  front-end/src/api/retrospective-req.ts
  front-end/src/components/agility/AgilityCanvas.vue
  front-end/src/components/agility/AgilityCanvasUI.vue
  front-end/src/components/agility/UI/ColorPickerOption.vue
  front-end/src/components/agility/UI/ToolsEditor.vue
  front-end/src/composables/useSocketRetro.ts
  front-end/src/lib/pixi-tools-v2/class/containerManager.ts
  front-end/src/lib/pixi-tools-v2/class/normalyzer.ts
  front-end/src/lib/pixi-tools-v2/class/socketManager.ts
  front-end/src/lib/pixi-tools-v2/class/textContainer.ts
  front-end/src/lib/pixi-tools-v2/model/model-constructor/textArea.ts
  front-end/src/lib/pixi-tools-v2/model/template.ts
  front-end/src/lib/pixi-tools-v2/plugins/containerDragPlugin.ts
  front-end/src/lib/pixi-tools-v2/plugins/managerDownloadPlugin.ts
  front-end/src/lib/pixi-tools-v2/plugins/viewportSocketPlugin.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-enums.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-serialize.ts
  front-end/src/lib/pixi-tools-v2/unsupported/textarea_html.ts
  front-end/src/lib/pixi-tools-v2/utils/colorsConvertor.ts
  front-end/src/lib/pixi-tools-v2/utils/dragAttachedLines.ts
  front-end/src/lib/pixi-tools-v2/utils/modelSerializer.ts
  front-end/src/lib/pixi-tools-v2/viewportUI.ts
  front-end/src/store/interfaces/project.interface.ts
  front-end/src/store/interfaces/retrospective.interface.ts
  front-end/src/store/interfaces/user.interface.ts
  front-end/src/store/modules/project.store.ts
Labels: codeball:needs-careful-review

#429 G7/feature/clean code
  back-end/src/base/articles/articles.service.ts
  front-end/package.json
  front-end/src/components/blog/AddArticles.vue
  front-end/src/components/blog/CardArticle.vue
  front-end/src/components/blog/DisplayArticles.vue
  front-end/src/components/blog/EditArticle.vue
  front-end/src/components/blog/MarkdownViewer.vue
  front-end/src/components/blog/ShowArticle.vue
  front-end/src/components/common/svg/Pause.vue
  front-end/src/components/common/svg/Validate.vue
  front-end/src/store/interfaces/article.interface.ts
  front-end/src/store/modules/article.store.ts
Labels: codeball:needs-careful-review

#424 G5/feature/material ideas
  front-end/src/assets/styles/components/add-ideas.css
  front-end/src/assets/styles/components/common/pop-up.css
  front-end/src/styles/pop-up-backdrop.css
  front-end/src/views/material-ideas/AddIdeas.vue
  front-end/src/views/material-ideas/Comments.vue
  front-end/src/views/material-ideas/DraftPdf.vue
  front-end/src/views/material-ideas/InfoLayout.vue
  front-end/src/views/material-ideas/PopUp.vue
Labels: codeball:needs-careful-review

#378 :add: alarm_timer
  front-end/src/assets/audio/retrospectiveAudio/bell_1.wav
  front-end/src/components/retrospective/Timer.vue
Labels: codeball:needs-careful-review

#433 Implement binding group lock with projects week WAITING FOR THE TRELLO BUT WORKS WITH PROJECT + RETRO
  back-end/src/base/calls/calls.controller.ts
  back-end/src/base/calls/calls.repository.ts
  back-end/src/base/calls/calls.service.ts
  back-end/src/base/courses/courses.controller.ts
  back-end/src/base/courses/courses.module.ts
  back-end/src/base/courses/courses.service.ts
  back-end/src/base/courses/interfaces/courses.interface.ts
  back-end/src/base/groups/groups.controller.ts
  back-end/src/base/groups/groups.module.ts
  back-end/src/base/groups/groups.service.ts
  back-end/src/base/groups/utils/createProject.ts
  back-end/src/base/retrospectives/retrospectives.service.ts
  front-end/src/components/RessourcesComponents/CoursDetails.vue
  front-end/src/components/RollCallComponents/GroupsComponent.vue
  front-end/src/components/retrospective/ChooseTemplate.vue
  front-end/src/components/retrospective/CreateRetro.vue
  front-end/src/store/course.store.ts
  front-end/src/store/interfaces/cours.interface.ts
  front-end/src/store/interfaces/course.interface.ts
  front-end/src/store/interfaces/retrospective.interface.ts
  front-end/src/store/modules/course.store.ts
  front-end/src/views/Retrospective.vue
Labels: codeball:needs-careful-review

#435 [Feature & Fix] Semi-Dynamic refresh for students list
  back-end/src/base/calls/calls.repository.ts
  back-end/src/base/calls/calls.service.ts
  front-end/src/components/RollCallComponents/StudentListComponent.vue
Labels: codeball:approved

#432 G5/feature/idea socket
  back-end/src/base/ideasComments/ideasComments.module.ts
  back-end/src/common/gateways/ideasComment.global.gateway.ts
  back-end/src/common/middlewares/socket.ideasComment.middleware.ts
  front-end/src/views/MaterialsView.vue
  front-end/src/views/material-ideas/Comments.vue
Labels: codeball:needs-careful-review

#449 Develop g5
  back-end/src/base/ideasComments/ideasComments.module.ts
  back-end/src/common/gateways/ideasComment.global.gateway.ts
  back-end/src/common/middlewares/socket.ideasComment.middleware.ts
  front-end/src/components/materials/ButtonsMaterials.vue
  front-end/src/views/MaterialDashboardView.vue
  front-end/src/views/MaterialsView.vue
  front-end/src/views/material-ideas/Comments.vue
  front-end/src/views/materialDashboard/BarChart.vue
  front-end/src/views/materialDashboard/DoughnutChart.vue
  front-end/src/views/materialDashboard/NbMaterial.vue
Labels: codeball:needs-careful-review

#448 Feat/g10/emoji picker
  back-end/package-lock.json
  back-end/package.json
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/RollCallComponents/Chat.vue
Labels: codeball:needs-careful-review

#454 Implement every blueprint with the text
  front-end/src/components/agility/modals/Persona.vue
  front-end/src/components/agility/persona/BuilderChallengesAndDifficulties.vue
  front-end/src/components/agility/persona/BuilderGoalAndNeed.vue
  front-end/src/components/agility/persona/BuilderProfile.vue
  front-end/src/components/agility/persona/BuilderSkillsAndCommentary.vue
  front-end/src/lib/pixi-tools-v2/blueprint/elevatorPitch.ts
  front-end/src/lib/pixi-tools-v2/blueprint/empathyMap.ts
  front-end/src/lib/pixi-tools-v2/blueprint/impactMapping.ts
  front-end/src/lib/pixi-tools-v2/blueprint/personas.ts
  front-end/src/lib/pixi-tools-v2/blueprint/pruneTheProjectTree.ts
  front-end/src/lib/pixi-tools-v2/class/containerManager.ts
  front-end/src/lib/pixi-tools-v2/class/framedContainer.ts
  front-end/src/lib/pixi-tools-v2/class/genericContainer.ts
  front-end/src/lib/pixi-tools-v2/class/lineContainer.ts
  front-end/src/lib/pixi-tools-v2/class/textContainer.ts
  front-end/src/lib/pixi-tools-v2/model/model-constructor/lineBezier.ts
  front-end/src/lib/pixi-tools-v2/model/model-constructor/textArea.ts
  front-end/src/lib/pixi-tools-v2/plugins/containerDragPlugin.ts
  front-end/src/lib/pixi-tools-v2/plugins/containerResizePlugin.ts
  front-end/src/lib/pixi-tools-v2/plugins/viewportSocketPlugin.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-aliases.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-serialize.ts
  front-end/src/lib/pixi-tools-v2/utils/dragAttachedLines.ts
  front-end/src/lib/pixi-tools-v2/utils/modelSerializer.ts
  front-end/src/lib/pixi-tools-v2/viewportUI.ts
  front-end/src/store/interfaces/project.interface.ts
  front-end/src/store/modules/project.store.ts
Labels: codeball:needs-careful-review

#453 [Feature] Add Emojis to the tchat
  back-end/package-lock.json
  back-end/package.json
  back-end/src/base/calls/calls.controller.ts
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/RollCallComponents/CallsComponent.vue
  front-end/src/components/RollCallComponents/Chat.vue
  front-end/src/components/RollCallComponents/MakeGroupsComponent.vue
  front-end/src/components/RollCallComponents/ReturnButtonComponent.vue
  front-end/src/layout/app/DrawerLayout.vue
Labels: codeball:needs-careful-review

#471 [Feature] - Move Groups to an other page
  front-end/src/components/RollCallComponents/MakeGroupsComponent.vue
  front-end/src/components/RollCallComponents/ReturnButtonComponent.vue
  front-end/src/layout/app/DrawerLayout.vue
  front-end/src/views/calls/GroupsView.vue
  front-end/src/views/calls/RollCallView.vue
Labels: codeball:approved

#476 add capitalize to title && change design validation tuto && change ju…
  back-end/src/base/articles/articles.service.ts
  front-end/src/components/blog/AddArticles.vue
  front-end/src/components/blog/CardArticle.vue
  front-end/src/components/blog/EditArticle.vue
  front-end/src/components/blog/MarkdownViewer.vue
  front-end/src/components/blog/ShowArticle.vue
  front-end/src/store/interfaces/article.interface.ts
  front-end/src/store/modules/article.store.ts
Labels: codeball:needs-careful-review

#479 G7/feature/statistique
  back-end/package-lock.json
  back-end/package.json
  back-end/src/base/articles/articles.controller.ts
  back-end/src/base/articles/articles.service.ts
  front-end/src/components/blog/Stats.vue
  front-end/src/router/index.ts
  front-end/src/store/interfaces/user.interface.ts
  front-end/src/store/modules/article.store.ts
  front-end/src/store/modules/user.store.ts
  front-end/src/views/BlogStatsView.vue
Labels: codeball:needs-careful-review

#491 fix(develop): Fix a crash
  front-end/src/components/blog/DisplayArticles.vue
  front-end/src/utils/pdfMake_vfs.ts
Labels: codeball:approved

#495 Develop g2
  back-end/src/base/articles/articles.controller.ts
  back-end/src/base/articles/articles.service.ts
  back-end/src/main.ts
  front-end/src/components/RessourcesComponents/AddCourse.vue
  front-end/src/components/RessourcesComponents/Cours.vue
  front-end/src/components/RessourcesComponents/CoursDetails.vue
  front-end/src/components/RessourcesComponents/OpenHouses.vue
  front-end/src/components/RessourcesComponents/OpenHousesDetails.vue
  front-end/src/components/RessourcesComponents/Ressources.vue
  front-end/src/components/blog/AddArticles.vue
  front-end/src/components/common/svg/Board.vue
  front-end/src/components/common/svg/Clipboard.vue
  front-end/src/store/interfaces/article.interface.ts
  front-end/src/store/interfaces/cours.interface.ts
  front-end/src/store/modules/article.store.ts
  front-end/src/store/modules/course.store.ts
  front-end/src/views/OpenHousesDetails.vue
Labels: codeball:needs-careful-review

#493 Develop g8
  front-end/src/components/retrospective/Board.vue
  front-end/src/components/retrospective/CreatePostit.vue
  front-end/src/components/retrospective/PassedRetrospectives.vue
  front-end/src/components/retrospective/Postit.vue
  front-end/src/components/retrospective/utils/RetroCard.vue
  front-end/src/components/retrospective/utils/SideBarParticipants.vue
  front-end/src/views/NewRetrospective.vue
Labels: codeball:needs-careful-review

#496 Develop g1
  back-end/src/app.module.ts
  back-end/src/base/boards/boards.controller.ts
  back-end/src/base/boards/boards.repository.ts
  back-end/src/base/boards/boards.service.ts
  back-end/src/base/boards/interfaces/boards.interface.ts
  back-end/src/base/calls/calls.controller.ts
  back-end/src/base/calls/calls.repository.ts
  back-end/src/base/calls/calls.service.ts
  back-end/src/base/courses/courses.controller.ts
  back-end/src/base/courses/courses.service.ts
  back-end/src/base/projects/interfaces/projects.interface.ts
  back-end/src/base/projects/projects.controller.ts
  back-end/src/base/projects/projects.repository.ts
  back-end/src/base/projects/projects.service.ts
  back-end/src/base/stories/interfaces/stories.interface.ts
  back-end/src/base/stories/stories.controller.ts
  back-end/src/base/stories/stories.module.ts
  back-end/src/base/stories/stories.repository.ts
  back-end/src/base/stories/stories.service.ts
  front-end/src/components/scrum/AddMemberForm.vue
  front-end/src/components/scrum/BacklogItem.vue
  front-end/src/components/scrum/BoardForm.vue
  front-end/src/components/scrum/EditProjectForm.vue
  front-end/src/components/scrum/EditTaskForm.vue
  front-end/src/components/scrum/ScrumBoard.vue
  front-end/src/components/scrum/ScrumMainPO.vue
  front-end/src/components/scrum/ScrumMainStudent.vue
  front-end/src/components/scrum/StoriesForm.vue
  front-end/src/components/scrum/TaskForm.vue
  front-end/src/router/index.ts
  front-end/src/views/OrganisationView.vue
  front-end/src/views/SprintsView.vue
Labels: codeball:needs-careful-review

#457 Download the frames as PDF
  front-end/src/components/agility/UI/DefaultSelectionBox.vue
  front-end/src/components/agility/UI/MiroSelectionBox.vue
  front-end/src/lib/pixi-tools-v2/blueprint/elevatorPitch.ts
  front-end/src/lib/pixi-tools-v2/blueprint/empathyMap.ts
  front-end/src/lib/pixi-tools-v2/blueprint/impactMapping.ts
  front-end/src/lib/pixi-tools-v2/blueprint/personas.ts
  front-end/src/lib/pixi-tools-v2/blueprint/pruneTheProjectTree.ts
  front-end/src/lib/pixi-tools-v2/class/framedContainer.ts
  front-end/src/lib/pixi-tools-v2/class/normalyzer.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-enums.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-serialize.ts
  front-end/src/lib/pixi-tools-v2/utils/base64codingFactoryLogo.ts
  front-end/src/lib/pixi-tools-v2/utils/base64codingToolsLogo.ts
  front-end/src/lib/pixi-tools-v2/utils/generatePdf.ts
  front-end/src/store/interfaces/project.interface.ts
  front-end/src/store/modules/project.store.ts
Labels: codeball:needs-careful-review

#500 Download the pdf
  front-end/src/components/agility/UI/DefaultSelectionBox.vue
  front-end/src/components/agility/UI/MiroSelectionBox.vue
  front-end/src/lib/pixi-tools-v2/blueprint/elevatorPitch.ts
  front-end/src/lib/pixi-tools-v2/blueprint/empathyMap.ts
  front-end/src/lib/pixi-tools-v2/blueprint/impactMapping.ts
  front-end/src/lib/pixi-tools-v2/blueprint/personas.ts
  front-end/src/lib/pixi-tools-v2/blueprint/pruneTheProjectTree.ts
  front-end/src/lib/pixi-tools-v2/class/framedContainer.ts
  front-end/src/lib/pixi-tools-v2/class/normalyzer.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-enums.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-serialize.ts
  front-end/src/lib/pixi-tools-v2/utils/base64codingFactoryLogo.ts
  front-end/src/lib/pixi-tools-v2/utils/base64codingToolsLogo.ts
  front-end/src/lib/pixi-tools-v2/utils/generatePdf.ts
  front-end/src/store/interfaces/project.interface.ts
  front-end/src/store/modules/project.store.ts
Labels: codeball:needs-careful-review

#507 Feature/connection between group
  front-end/src/components/RessourcesComponents/AddCourse.vue
  front-end/src/components/RessourcesComponents/CoursDetails.vue
  front-end/src/components/RessourcesComponents/OpenHousesDetails.vue
  front-end/src/components/blog/AddArticles.vue
  front-end/src/components/common/svg/ArrowLeft.vue
  front-end/src/components/common/svg/Book.vue
  front-end/src/store/interfaces/article.interface.ts
  front-end/src/store/interfaces/cours.interface.ts
  front-end/src/store/modules/article.store.ts
  front-end/src/store/modules/course.store.ts
Labels: codeball:needs-careful-review

#509 Develop g2
  front-end/src/components/RessourcesComponents/AddCourse.vue
  front-end/src/components/RessourcesComponents/CoursDetails.vue
  front-end/src/components/RessourcesComponents/OpenHousesDetails.vue
  front-end/src/components/blog/AddArticles.vue
  front-end/src/components/common/svg/ArrowLeft.vue
  front-end/src/components/common/svg/Book.vue
  front-end/src/store/interfaces/article.interface.ts
  front-end/src/store/interfaces/cours.interface.ts
  front-end/src/store/modules/article.store.ts
  front-end/src/store/modules/course.store.ts
Labels: codeball:needs-careful-review
