Repository CodingFactory-Repos/Coding-Tools, pull requests merged in 2023-03, with the labels that each got.

#51 Implement Mailjet module with universal email templating
  back-end/.env.example
  back-end/package-lock.json
  back-end/package.json
  back-end/src/auth/auth.controller.ts
  back-end/src/auth/auth.module.ts
  back-end/src/auth/auth.service.ts
  back-end/src/auth/dto/auth.dto.ts
  back-end/src/auth/events/auth.events.req.ts
  back-end/src/auth/events/auth.events.ts
  back-end/src/auth/utils/auth.security.ts
  back-end/src/base/materials/materials.controller.ts
  back-end/src/base/users/interfaces/users.interface.ts
  back-end/src/base/users/users.repository.ts
  back-end/src/common/helpers/string.helper.ts
  back-end/src/common/providers/interfaces/events.interface.ts
  back-end/src/common/providers/mailjet.provider.ts
  back-end/src/common/providers/mailjet.service.ts
  back-end/src/config/config.ts
  back-end/src/config/env.validator.ts
  back-end/src/config/interface/config.interface.ts
  back-end/src/external-modules/mailjet/mailjet.interface.ts
  back-end/src/external-modules/mailjet/mailjet.module.ts
  back-end/src/external-modules/mailjet/mailjet.service.ts
Labels: enhancement, merge when passing, codeball:needs-careful-review

#156 Develop g8
  back-end/src/auth/utils/auth.cookie.ts
Labels: codeball:needs-careful-review

#154 Adding the creation of materials and the pdf
  front-end/package-lock.json
  front-end/package.json
  front-end/src/views/MaterialsView.vue
Labels: merge when passing

#164 Updating devprotocol for enable
  README.md
Labels: codeball:approved

#178 G5/feature/material card
  back-end/src/base/materials/interfaces/materials.interface.ts
  back-end/src/base/materials/materials.controller.ts
  back-end/src/base/materials/materials.module.ts
  back-end/src/base/materials/materials.repository.ts
  back-end/src/base/materials/materials.service.ts
  front-end/package.json
  front-end/src/components/common/Modal.vue
  front-end/src/components/materials/ButtonsMaterials.vue
  front-end/src/components/materials/DetailsMaterials.vue
  front-end/src/components/materials/FormMaterials.vue
  front-end/src/components/materials/ListMaterials.vue
  front-end/src/components/materials/MaterialCard.vue
  front-end/src/views/MaterialsView.vue
Labels: codeball:needs-careful-review

#182 Implement the ui button static zoom for the canvas.
  front-end/src/components/agility/AgilityCanvas.vue
  front-end/src/components/agility/UI/SceneMode.vue
  front-end/src/components/common/svg/Shrink.vue
  front-end/src/lib/pixi-tools/scene.ts
  front-end/src/store/interfaces/project.interface.ts
  front-end/src/store/modules/project.store.ts
Labels: enhancement

#192 G5/feature/search bar filter materials
  back-end/src/base/materials/materials.controller.ts
  front-end/src/components/materials/ListMaterials.vue
  front-end/src/store/interfaces/material.interface.ts
  front-end/src/store/modules/material.store.ts
  front-end/src/views/MaterialsView.vue
Labels: codeball:needs-careful-review

#200 Add alt for every image + add th in the table and a caption
  front-end/src/components/materials/BorrowHistoryMaterials.vue
  front-end/src/components/materials/MaterialCard.vue
  front-end/src/views/SprintsView.vue
Labels: codeball:needs-careful-review
