Repository CodingFactory-Repos/Coding-Tools, pull requests merged in 2023-05, with the labels that each got.

#245 Implement the save of a canvas project and add a better sync support
  back-end/package-lock.json
  back-end/package.json
  back-end/src/base/canvasRoom/canvasRoom.controller.ts
  back-end/src/base/canvasRoom/canvasRoom.service.ts
  back-end/src/base/canvasRoom/interfaces/canvasRoom.interface.ts
  back-end/src/base/canvasRoom/interfaces/ws.canvasRoom.interface.ts
  back-end/src/base/canvasRoom/utils/canvasRoom.projection.ts
  back-end/src/common/gateways/canvas.global.gateway.ts
  front-end/src/api/agility-req.ts
  front-end/src/components/agility/AgilityCanvas.vue
  front-end/src/components/agility/UI/CanvasLoader.vue
  front-end/src/layout/app/DrawerLayout.vue
  front-end/src/lib/pixi-tools-v2/class/containerManager.ts
  front-end/src/lib/pixi-tools-v2/class/framedContainer.ts
  front-end/src/lib/pixi-tools-v2/class/genericContainer.ts
  front-end/src/lib/pixi-tools-v2/class/normalyzer.ts
  front-end/src/lib/pixi-tools-v2/class/socketManager.ts
  front-end/src/lib/pixi-tools-v2/model/model-constructor/circle.ts
  front-end/src/lib/pixi-tools-v2/model/model-constructor/rectangle.ts
  front-end/src/lib/pixi-tools-v2/model/model-ui-constructor/border.ts
  front-end/src/lib/pixi-tools-v2/model/model-ui-constructor/grid.ts
  front-end/src/lib/pixi-tools-v2/model/model-ui-constructor/handle.ts
  front-end/src/lib/pixi-tools-v2/model/model-ui-constructor/hitArea.ts
  front-end/src/lib/pixi-tools-v2/plugins/containerDragPlugin.ts
  front-end/src/lib/pixi-tools-v2/plugins/containerResizePlugin.ts
  front-end/src/lib/pixi-tools-v2/plugins/viewportSocketPlugin.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-class.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-serialize.ts
  front-end/src/lib/pixi-tools-v2/utils/modelBounds.ts
  front-end/src/store/interfaces/agility.interface.ts
  front-end/src/store/modules/agility.store.ts
  front-end/src/views/app/AgilityProject.vue
Labels: merge when passing, codeball:needs-careful-review

#246 [Feature] - Add the creation of groups
  back-end/src/base/calls/calls.controller.ts
  back-end/src/base/calls/calls.repository.ts
  back-end/src/base/calls/calls.service.ts
  back-end/src/common/decorators/catch.decorator.ts
  front-end/src/components/RollCallComponents/GroupsComponent.vue
  front-end/src/components/RollCallComponents/MakeGroupsComponent.vue
  front-end/src/lib/pixi-tools/docs/assets/js/index.js
Labels: codeball:needs-careful-review

#247 Fix the frame context when switching tabulation, it was broken with the recent changes
  front-end/src/lib/pixi-tools-v2/class/framedContainer.ts
  front-end/src/lib/pixi-tools-v2/types/pixi-class.ts
  front-end/src/store/modules/project.store.ts
Labels: merge when passing

#253 Update auto-develop with G1-develop
  back-end/src/base/sprints/interfaces/sprints.interface.ts
  back-end/src/base/sprints/sprints.controller.ts
  back-end/src/base/sprints/sprints.module.ts
  back-end/src/base/sprints/sprints.repository.ts
  back-end/src/base/sprints/sprints.service.ts
  front-end/src/api/scrum-req.ts
  front-end/src/components/NewGroup.vue
  front-end/src/components/NewSprint.vue
  front-end/src/views/OrganisationView.vue
  front-end/src/views/SprintsView.vue
Labels: codeball:needs-careful-review

#257 [Feature] - Creation of random groups
  back-end/src/auth/auth.service.ts
  back-end/src/base/calls/calls.controller.ts
  back-end/src/base/calls/calls.repository.ts
  back-end/src/base/calls/calls.service.ts
  back-end/src/base/users/interfaces/users.interface.ts
  back-end/src/common/decorators/role.decorator.ts
  back-end/src/common/guards/role.guard.ts
  front-end/src/components/RollCallComponents/GroupsComponent.vue
Labels: codeball:needs-careful-review

#252 G5 - Heavy review with TODO comments and some types fix + axios fix.
  back-end/src/base/calls/calls.repository.ts
  back-end/src/base/materials/dto/materials.dto.ts
  back-end/src/base/materials/interfaces/materials.interface.ts
  back-end/src/base/materials/materials.controller.ts
  back-end/src/base/materials/materials.module.ts
  back-end/src/base/materials/materials.service.ts
  front-end/src/api/material-req.ts
  front-end/src/components/materials/BorrowHistoryMaterials.vue
  front-end/src/components/materials/ButtonsMaterials.vue
  front-end/src/components/materials/DetailsMaterials.vue
  front-end/src/components/materials/FormMaterials.vue
  front-end/src/components/materials/ListMaterials.vue
  front-end/src/components/materials/MaterialCard.vue
  front-end/src/store/interfaces/material.interface.ts
  front-end/src/store/modules/material.store.ts
  front-end/src/views/OrganisationView.vue
Labels: codeball:needs-careful-review

#306 Regroup commits
  back-end/src/base/calls/calls.repository.ts
  back-end/src/base/materials/dto/materials.dto.ts
  back-end/src/base/materials/interfaces/materials.interface.ts
  back-end/src/base/materials/materials.controller.ts
  back-end/src/base/materials/materials.module.ts
  back-end/src/base/materials/materials.service.ts
  front-end/src/api/material-req.ts
  front-end/src/components/materials/BorrowHistoryMaterials.vue
  front-end/src/components/materials/ButtonsMaterials.vue
  front-end/src/components/materials/DetailsMaterials.vue
  front-end/src/components/materials/FormMaterials.vue
  front-end/src/components/materials/ListMaterials.vue
  front-end/src/components/materials/MaterialCard.vue
  front-end/src/store/interfaces/material.interface.ts
  front-end/src/store/modules/material.store.ts
Labels: merge when passing, codeball:needs-careful-review

#309 Merge pre-develop to develop G6
  back-end/.gitignore
  back-end/docker-compose.prod.yml
  back-end/docker-compose.yml
  back-end/package-lock.json
  back-end/src/auth/auth.service.ts
  back-end/src/base/materials/materials.module.ts
  back-end/src/base/users/users.service.ts
  front-end/src/components/account/AccountRelatedProfile.vue
  front-end/src/store/interfaces/template.interfaces.ts
  front-end/src/store/modules/agility.store.ts
  front-end/src/store/modules/auth.store.ts
  front-end/src/store/modules/project.store.ts
  front-end/src/store/modules/template.store.ts
  front-end/src/views/app/RelatedProfileView.vue
Labels: merge when passing, codeball:needs-careful-review
